kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  label:
    app: hello-openshift
  name: hello-openshift
  labels:
    build: hello-openshift
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'hello-openshift:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
  postCommit: {}
  source:
    type: Git
    git:
      uri:

---

  kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    name: hello-openshift
    labels:
      app: hello-openshift
  spec:
    lookupPolicy:
      local: false
